### ISSUE TITLE
Python core dumped error

### ISSUE THREAD

**Issue by arshpreetsingh** [mjucker/pv_atmos#1]
I am using pv_atmos on Ubuntu14.04.4, I have installed Paraview version 4.0.1 using apt package manager and both of the examples returns following error and crashes:

Error in `python': corrupted double-linked list: 0x0000000004f97060 **\* Aborted (core dumped)

I am also not able to see any images/animation. Please let me know if there is any other help I can bring there?

**Comment by mjucker** [comment]
Sorry to get back to you after this enormous amount of time... Will do better in the future.
Is this still an issue? Can you run the Paraview GUI and add things like a cube or a sphere? If so, do you run the examples in the Python Shell of the GUI or as a script?

**Comment by mjucker** [comment]
Closing the issue. Please re-open a new issue if problem persists with newer Paraview versions.
